/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author von
 */
public class ui extends javax.swing.JFrame {

    /**
     * Creates new form ui
     */
    public ui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        track = new javax.swing.JTextField();
        comms = new javax.swing.JTextField();
        uploadDate = new javax.swing.JTextField();
        accomp = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        personel = new javax.swing.JComboBox<>();
        receive = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Pbutton = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Comment");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 210, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Recepient");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 116, 140, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Upload date");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 162, 120, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Accomplished");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 202, 150, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Personel");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 294, 200, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Document type");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 248, 200, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Tracking Number");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 64, 160, 40));

        track.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackActionPerformed(evt);
            }
        });
        jPanel2.add(track, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 130, -1));
        jPanel2.add(comms, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 250, 40));
        jPanel2.add(uploadDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 130, -1));
        jPanel2.add(accomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 130, -1));
        jPanel2.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 130, -1));

        personel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelActionPerformed(evt);
            }
        });
        jPanel2.add(personel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 120, -1));
        jPanel2.add(receive, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 130, 30));

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        Pbutton.setText("Update List");
        Pbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(Pbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        delete1.setText("Delete");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        jPanel2.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        jLabel1.setText("Document ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public String docuID;
public String personID;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tracking = track.getText();
        String recepient = receive.getText();
        String Udate = uploadDate.getText();
        String accomplised = accomp.getText();
        String docu = type.getText();
        
         String url = "jdbc:mysql://localhost:3306/dms";
        String username = "root";
        String password = "";
        
       
        try{
            Connection conn = DriverManager.getConnection(url,username,password);
       PreparedStatement p = null;
         p = conn.prepareStatement("INSERT INTO documents (Tracking_num, Target_Recepient , Upload_date , Accomplished ,Document_Type) VALUES (?,?,?,?,?)");
         p.setString(1, tracking);
          p.setString(2, recepient);
           p.setString(3, Udate);
            p.setString(4, accomplised);
             p.setString(5, docu);
             p.executeUpdate();
             
             
             //get docu id and personel ID
             PreparedStatement p2 = null;
            
            
             String getid = "SELECT * FROM documents WHERE Tracking_num = (?)";
          
             p2 = conn.prepareStatement(getid);
             p2.setString(1, tracking);
             
              ResultSet r = p2.executeQuery();
              if(r.next()){
                  System.out.println();
                  docuID  = r.getString("Document_ID");
            
                  
              }
              System.out.println(docuID);
                     
             //get personel id
                 PreparedStatement p3 = null;
              String person = (String) personel.getSelectedItem();
                String getid2 = "SELECT * FROM personel WHERE First_name = (?)";
                p3 = conn.prepareStatement(getid2);
                p3.setString(1, person);
                
         ResultSet r2 = p3.executeQuery();
       while(r2.next()){
       
       
       personID = r2.getString("Personel_ID");
       } 
       /// insert comment 
       PreparedStatement commentIns = null;
       String sql3 = "INSERT INTO comment (Document_ID, Personel_ID , Comment) VALUES (?, ? , ? )";
       commentIns = conn.prepareStatement(sql3);
       commentIns.setString(1,docuID );
       commentIns.setString(2,personID );
        commentIns.setString(3,comms.getText() );
        commentIns.execute();
      
       
         
        
          JOptionPane.showMessageDialog(null, "DONE", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Failed", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void personelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelActionPerformed
          
     
        
    }//GEN-LAST:event_personelActionPerformed

    private void PbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PbuttonActionPerformed
 String url = "jdbc:mysql://localhost:3306/dms";
        String username = "root";
        String password = "";
        try{
            Connection conn = DriverManager.getConnection(url,username,password);
         Statement statement = conn.createStatement();
         ResultSet resultset = statement.executeQuery("Select * FROM personel");
        while(resultset.next()){
         String data = resultset.getString("First_name");
         personel.addItem(data);
        
        
        }
        
        }
        
        catch(Exception e){
        
        
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_PbuttonActionPerformed

    private void trackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trackActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed

 String url = "jdbc:mysql://localhost:3306/dms";
        String username = "root";
        String password = "";
        PreparedStatement prt = null;
        PreparedStatement prt2 = null;
        String IDdoc = ID.getText();
        try{
            //delete documents
            Connection conn = DriverManager.getConnection(url,username,password);
        String q = "Delete FROM documents where Document_ID = (?)";
        prt = conn.prepareStatement(q);
        prt.setString(1, IDdoc);
        prt.execute();
        //delete comments
        String b = "Delete FROM comment where Document_ID = (?)";
        prt2 = conn.prepareStatement(b);
        prt2.setString(1, IDdoc);
        prt2.execute();
        
         JOptionPane.showMessageDialog(null, "Deleted", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        }
        
        catch(Exception e){
        
        
        }






        // TODO add your handling code here:
    }//GEN-LAST:event_delete1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        track.setText("");
        receive.setText("");
        uploadDate.setText("");
        accomp.setText("");
        type.setText("");
        comms.setText("");
       
    }//GEN-LAST:event_clearActionPerformed

    
    
    
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ui().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ID;
    private javax.swing.JButton Pbutton;
    public javax.swing.JTextField accomp;
    private javax.swing.JButton clear;
    private javax.swing.JTextField comms;
    private javax.swing.JButton delete1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JComboBox<String> personel;
    public javax.swing.JTextField receive;
    public javax.swing.JTextField track;
    public javax.swing.JTextField type;
    private javax.swing.JButton update;
    public javax.swing.JTextField uploadDate;
    // End of variables declaration//GEN-END:variables
}
